### PR TITLE
Overview summary should have export option 

### PR DESCRIPTION
**Pull request by azaddhirajkumar**

### CODE REVIEW

**Review by deniswsrosa — CHANGES_REQUESTED** [review]
- Clicked on "export" and nothing happened.
- The task needs to run as a background job ( ProgressManager.getInstance().run(new Task.Backgroundable() - Check CBExport.java
- You need to ask the User where he wants to save the file. There are a number of places where we do that.

The task is not finished yet.

**Review by deniswsrosa — CHANGES_REQUESTED** [review]
The code is screaming warnings, a LOT of copy and paste, and "ifs" that will always be false. The PDF also has bugs.

**Comment by deniswsrosa** [comment]
@azaddhirajkumar Code quality needs to improve considerably. Did you completely ignore all warnings? **The PDF has a bug that you should have caught before releasing it for review.**  
Screenshot 2023-11-20 at 16 38 10

Some pages are blank. Making sure that your code works as expected **is the number 1 rule**.

**Comment by azaddhirajkumar** [comment]
Created a new PR for this issue as the current branch had problems.

**Pull request closed without merging**
