### PR TITLE
DA-377: CBL Import Wizard

### PR DESCRIPTION
**Pull request by teetangh**

### CODE REVIEW

**Comment by deniswsrosa** [comment]
Something is wrong in your layout with the titledSeparator "Target" as the line doesn't extend to the same length as the fields bellow.
The same is valid for the field for the "Select the Dataser" . It should have the same width as the fields bellow.


Screenshot 2023-11-24 at 20 16 43

**Comment by deniswsrosa** [comment]
If I start typing and delete what I have written, there is still some remaining letter in the key preview
Screenshot 2023-11-24 at 20 20 36

**Comment by deniswsrosa** [comment]
Once I clean the "Custom Expression" and click on "Previous", both "previous" and "next" buttons are disabled:
Screenshot 2023-11-24 at 20 22 37

**Comment by deniswsrosa** [comment]
#UUID# preview is not working
Screenshot 2023-11-24 at 20 24 34

**Comment by deniswsrosa** [comment]
Once the data is imported, we should at least show an alert saying that the import was successful.

**Review by deniswsrosa — CHANGES_REQUESTED** [review]
Few adjustments in the UI and the flow are needed.

**Comment by teetangh** [comment]
> Something is wrong in your layout with the titledSeparator "Target" as the line doesn't extend to the same length as the fields bellow. The same is valid for the field for the "Select the Dataser" . It should have the same width as the fields bellow.
> 
> Screenshot 2023-11-24 at 20 16 43

image

**Comment by teetangh** [comment]
> If I start typing and delete what I have written, there is still some remaining letter in the key preview Screenshot 2023-11-24 at 20 20 36

fixed it now
image
image

**Comment by teetangh** [comment]
> Once I clean the "Custom Expression" and click on "Previous", both "previous" and "next" buttons are disabled in the first panel: Screenshot 2023-11-24 at 20 22 37

fixed it now
image
image

**Comment by teetangh** [comment]
> #UUID# preview is not working. Make sure that it also works when you import the document Screenshot 2023-11-24 at 20 24 34

Fixed it now

image

image

**Comment by teetangh** [comment]
> Once the data is imported, we should at least show an alert saying that the import was successful.

Fixed it now
image

**Review by deniswsrosa — APPROVED** [review]

**Pull request merged**
