### PR TITLE
Virtual files

### PR DESCRIPTION
**Pull request by chedim**
Implements in-memory document editing using customized `VirtualFile` and `VirtualFileSystem` implementation.

### CODE REVIEW

**Review by deniswsrosa — CHANGES_REQUESTED** [review]
Could you also remove in this PR the call and code for GitIgnore.updateGitIgnore? It is not needed anymore.
There are also some methods like findOrCreateFolder that references "cbcache". They also need to be removed. Same for Dataloader.cleancache

**Review by deniswsrosa — CHANGES_REQUESTED** [review]
Found some bugs, checkout my comments

**Comment by deniswsrosa** [comment]
- The JSON document is not being formatted when it is opened.
- The following process threw the error in the image: 1) Open a document in the plugin, 2) change the same document on Couchbase's Web Console, 3) Change the document in the plugin and try to save it, 5) the popup will appear, then I chose the server's version instead of mine, 5) Got the following error:
Screenshot 2023-10-20 at 20 55 51

**Comment by chedim** [comment]
Fixed, @deniswsrosa

**Pull request merged**
